//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pexels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutHeaders
    {
        public int Id { get; set; }
        public string HeadTitle { get; set; }
        public string HeadText { get; set; }
        public string HeadBackground { get; set; }
    }
}
