//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pexels.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PexelsEntities : DbContext
    {
        public PexelsEntities()
            : base("name=PexelsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Settings> Settings { get; set; }
        public virtual DbSet<AboutUs> AboutUs { get; set; }
        public virtual DbSet<Discovers> Discovers { get; set; }
        public virtual DbSet<Homes> Homes { get; set; }
        public virtual DbSet<PopularPhotos> PopularPhotos { get; set; }
        public virtual DbSet<PopularSearches> PopularSearches { get; set; }
        public virtual DbSet<AboutHeaders> AboutHeaders { get; set; }
        public virtual DbSet<LisenceHeader> LisenceHeader { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Likes> Likes { get; set; }
        public virtual DbSet<LisenceAllows> LisenceAllows { get; set; }
        public virtual DbSet<LisenceCards> LisenceCards { get; set; }
        public virtual DbSet<LisenceNotAllows> LisenceNotAllows { get; set; }
        public virtual DbSet<FaqNews> FaqNews { get; set; }
        public virtual DbSet<FaqUploads> FaqUploads { get; set; }
        public virtual DbSet<FaqHeaders> FaqHeaders { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
