//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pexels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Likes
    {
        public int Id { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> PhotoId { get; set; }
    
        public virtual Photos Photos { get; set; }
    }
}
