//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pexels.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopularSearches
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Desc { get; set; }
        public string CollectionPhoto { get; set; }
        public string CollectionTitle { get; set; }
        public string CollectionIcon { get; set; }
    }
}
